apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jobscout
resources:
- scanner-cronjob.yaml
- application-writer-deployment.yaml
- application-writer-service.yaml
- obsidian-writer-deployment.yaml
- obsidian-writer-service.yaml
images:
- name: ghcr.io/charemma/agentic-job-scout-application-writer
  newName: ghcr.io/charemma/agentic-job-scout-application-writer
  newTag: latest
- name: ghcr.io/charemma/agentic-job-scout-obsidian-writer
  newName: ghcr.io/charemma/agentic-job-scout-obsidian-writer
  newTag: latest
- name: ghcr.io/charemma/agentic-job-scout-scanner
  newName: ghcr.io/charemma/agentic-job-scout-scanner
  newTag: latest
